var result1 = [{
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT OVERALL / CONSULTATION / LABARATORY / PATHOLOGY / XRAY",
        cust_ben_code: "",
        std_pool_number: 1,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT DENTAL",
        cust_ben_code: "",
        std_pool_number: 2,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT OPTICAL OR OUTPATIENT OPTICAL & DENTAL",
        cust_ben_code: "",
        std_pool_number: 3,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT FRAMES",
        cust_ben_code: "",
        std_pool_number: 4,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT PRE-EXISTING AND CHRONIC & HIV / AIDS CONDITIONS ",
        cust_ben_code: "",
        std_pool_number: 5,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT CONGENITAL OR NEO NATAL COVER OR CHILDBITH OR PREMATURITY COVER",
        cust_ben_code: "",
        std_pool_number: 6,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "ANTE AND POST NATAL CARE / OUT PATIENT MATERNITY",
        cust_ben_code: "",
        std_pool_number: 7,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IMMUNIZATION / VACCINES",
        cust_ben_code: "",
        std_pool_number: 8,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT PAP SMEAR/ PSA TEST/ CIRCUMCISION",
        cust_ben_code: "",
        std_pool_number: 9,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT PSYCHIATRIC AILMENTS / COUNSELING/REHABILITATION",
        cust_ben_code: "",
        std_pool_number: 10,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT HEALTH CHECKUP / WELLBEING BENEFIT",
        cust_ben_code: "",
        std_pool_number: 11,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "WORK PLACE PROGRAM/WELLNESS PROGRAM",
        cust_ben_code: "",
        std_pool_number: 12,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT  MEDICAL APPLICANCES - PHYSIOTHERAPY/ PROTHESIS/ WHEELCHAIRS/HEARING AIDS",
        cust_ben_code: "",
        std_pool_number: 13,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "STAFF CLINIC BENEFIT",
        cust_ben_code: "",
        std_pool_number: 14,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT RESERVE",
        cust_ben_code: "",
        std_pool_number: 15,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "ACUTE MEDICATION",
        cust_ben_code: "",
        std_pool_number: 16,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "CHRONIC MEDICATION",
        cust_ben_code: "",
        std_pool_number: 17,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT OVERALL / HOSPITALIZATION/ACCOMODATION",
        cust_ben_code: "",
        std_pool_number: 18,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "POST HOSPITALIZATION",
        cust_ben_code: "",
        std_pool_number: 19,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT PRE-EXISTING & RELATED CONDITIONS",
        cust_ben_code: "",
        std_pool_number: 20,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT HIV & RELATED CONDITIONS",
        cust_ben_code: "",
        std_pool_number: 21,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT CONGENITAL/CHILDBRITH COVER/ NEO NATAL CONDITIONS/ PREMATURITY EXPENSES",
        cust_ben_code: "",
        std_pool_number: 22,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT NON ACCIDENTAL DENTAL",
        cust_ben_code: "",
        std_pool_number: 23,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT NON ACCIDENTAL OPTICAL/ OPTHAMOLOGY",
        cust_ben_code: "",
        std_pool_number: 24,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT ACCIDENTAL DENTAL/ EMERGENCY DENTAL TREATMENT FOLLOWING AN ACCIDENT",
        cust_ben_code: "",
        std_pool_number: 25,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT ACCIDENTAL OPTICAL/ EMERGENCY OPTICAL TREATMENT FOLLOWING AN ACCIDENT",
        cust_ben_code: "",
        std_pool_number: 26,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT NORMAL DELIVERY/ MATERNITY COVER",
        cust_ben_code: "",
        std_pool_number: 27,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "FIRST EVER EMERGENCY CEASEREAN",
        cust_ben_code: "",
        std_pool_number: 28,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "ELECTIVE CEASEREAN SECTION / MATERNITY COMPLICATIONS (POST DELIVERY)",
        cust_ben_code: "",
        std_pool_number: 29,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT INTERNAL AND EXTERNAL PROSTHESES (EXTERNAL AIDS)",
        cust_ben_code: "",
        std_pool_number: 30,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT PHYSIOTHERAPY ",
        cust_ben_code: "",
        std_pool_number: 31,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT MAXILLOFACIAL SURGERY / ACCIDENT RELATED RECONSTRUCTIVE SURGERY",
        cust_ben_code: "",
        std_pool_number: 32,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT PSYCHIATRY AND PSYCHOTHERAPY TREATMENT",
        cust_ben_code: "",
        std_pool_number: 33,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "RADIOLOGY & PATHOLOGY / MRI AND CT SCANS (Can either be Inpatient or an Outpatient benefit depending on the customers preference)",
        cust_ben_code: "",
        std_pool_number: 34,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT DAY CARE SURGERY",
        cust_ben_code: "",
        std_pool_number: 35,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT ONCOLOGY/CANCER TREATMENT",
        cust_ben_code: "",
        std_pool_number: 36,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT ORGAN TRANSPLANT / MAJOR ORGAN TRANSPLANT EXCLUDING THE COST OF ORGAN DONOR",
        cust_ben_code: "",
        std_pool_number: 37,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT PRESCRIPTION DRUGS AND MATERIALS",
        cust_ben_code: "",
        std_pool_number: 38,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT ROAD AND AIR EVACUATION / IN PATIENT OVERSEAS REFERRAL TREATMENT",
        cust_ben_code: "",
        std_pool_number: 39,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT EXTERNAL MEDICAL APPLIANCES",
        cust_ben_code: "",
        std_pool_number: 40,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT GYNAECOLOGICAL SURGERY",
        cust_ben_code: "",
        std_pool_number: 41,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "KIDNEY DIALYSIS  (Can either be Inpatient or an Outpatient benefit depending on the customers preference)",
        cust_ben_code: "",
        std_pool_number: 42,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT ARTHRITIS/ASTHMA/THYROID DISEASE",
        cust_ben_code: "",
        std_pool_number: 43,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT CARDIOLOGY",
        cust_ben_code: "",
        std_pool_number: 44,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT HYPERTENSIONS/DIABETES/LIPEDEMIA/BLOOD DISORDERS",
        cust_ben_code: "",
        std_pool_number: 45,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT PATIENT FAMILY PLANNING",
        cust_ben_code: "",
        std_pool_number: 46,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT HDU AND ICU",
        cust_ben_code: "",
        std_pool_number: 47,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "REHABILITATION DUE TO ACCIDENT RELATED CASES",
        cust_ben_code: "",
        std_pool_number: 48,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT RESERVE / EXCESS OF LOSS",
        cust_ben_code: "",
        std_pool_number: 49,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT NON ACCIDENT RELATED MAXILLOFACIAL SURGERY",
        cust_ben_code: "",
        std_pool_number: 50,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "ADDITIONAL BENEFIT",
        cust_ben_code: "",
        std_pool_number: 51,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "ADDITIONAL BENEFIT",
        cust_ben_code: "",
        std_pool_number: 52,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "ADDITIONAL BENEFIT",
        cust_ben_code: "",
        std_pool_number: 53,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "ADDITIONAL BENEFIT",
        cust_ben_code: "",
        std_pool_number: 54,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "CASH",
        cust_ben_code: "",
        std_pool_number: 55,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "IN PATIENT GRAND POOL",
        cust_ben_code: "",
        std_pool_number: 56,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OUT PATIENT GRAND POOL",
        cust_ben_code: "",
        std_pool_number: 57,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "OFFLINE BILLING BENEFIT",
        cust_ben_code: "",
        std_pool_number: 58,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "NHIF",
        cust_ben_code: "",
        std_pool_number: 59,
        id: 0,
    },
    {
        pol_id: null,
        cat_id: null,
        user_id: 0,
        cust_id: 0,
        insert_time: null,
        is_error: null,
        error_msg: null,
        cust_ben_desc: "",
        map_pool_count: 0,
        map_itemgroup_count: 0,
        smart_ben_code: "",
        smart_ben_desc: "NHIF",
        cust_ben_code: "",
        std_pool_number: 60,
        id: 0,
    },
];

var result2 = [{
        Cat_Code: "A",
        Pool_Number: 1,
        Pool_Description: "OUT PATIENT OVERALL (ALL BABY VACCINES COVERED FOR CHILDREN UP TO 5 YEARS)",
        Smart_Pool_Number: 1,
        Payer_Benefit_Code: "OPO",
        Payer_Benefit_Desc: "OUTPATIENT OVERALL",
    },
    {
        Cat_Code: "A",
        Pool_Number: 52,
        Pool_Description: "OUTPATIENT ACUTE MEDICATION/CHRONIC MEDICATION",
        Smart_Pool_Number: 2,
        Payer_Benefit_Code: "OPD",
        Payer_Benefit_Desc: "OUTPATIENT DENTAL",
    },
    {
        Cat_Code: "A",
        Pool_Number: 51,
        Pool_Description: "OUTPATIENT RADIOLOGY & PATHOLOGY MRI/CT SCANS (PRE-AUTHORIZATION REQUIRED)",
        Smart_Pool_Number: 3,
        Payer_Benefit_Code: "OPOPT",
        Payer_Benefit_Desc: "OUTPATIENT OPTICAL",
    },

    {
        Cat_Code: "B",
        Pool_Number: 6,
        Pool_Description: "OUTPATIENT CONGENITAL AND PRE-MATURITY CONDITIONS",
    },
    {
        Cat_Code: "B",
        Pool_Number: 2,
        Pool_Description: "OUT PATIENT DENTAL (PRE-AUTHORIZATION REQUIRED)",
    },



    {
        Cat_Code: "B",
        Pool_Number: 23,
        Pool_Description: "INPATIENT DENTAL ILLNESS",
    },
    {
        Cat_Code: "B",
        Pool_Number: 24,
        Pool_Description: "INPATIENT OPTICAL ILLNESS ",
    },

];



const mapItm = (arr1, arr2) => {
    let arr3 = arr2.filter(el => {
        return el.Smart_Pool_Number != undefined && el.Payer_Benefit_Code != undefined
    })
    if (arr1.length > 0) {
        arr1.map(item => {
            for (let i = 0; i < arr3.length; i++) {
                if (item.std_pool_number == arr3[i].Smart_Pool_Number) {
                    console.log(item.std_pool_number + " === " + arr3[i].Smart_Pool_Number)
                    item.cust_ben_code = arr3[i].Payer_Benefit_Code
                    item.cust_ben_desc = arr3[i].Payer_Benefit_Desc
                }
            }
        })
    }
}

mapItm(result1, result2)





// var result = result1
//     .map(function(o1) {
//         result2.map(function(o2) {
//             console.log(o2.Payer_Benefit_Code)
//             if (o1.std_pool_number === o2.Pool_Number) {
//                 o1.cust_ben_code = o2.Payer_Benefit_Code
//                 o1.cust_ben_desc = o2.Payer_Benefit_Desc
//             } // assumes unique id
//         });
//     })

// console.log(result)